### ISSUE TITLE
How to use custom calib data?

### ISSUE THREAD

**Issue by Juelianqvq** [HandH1998/QQQ#1]

**Comment by HandH1998** [comment]
修改quant_config/llama/*.yaml
![image](https://github.com/HandH1998/QQQ/assets/44199326/74e52aed-e982-45b8-8207-10340c37e828)

**Comment by HandH1998** [comment]
> > quant_config
> 
> @HandH1998 May I ask what's the purpose of `gptq` option below?

QQQ first employs smoothing, then employs gptq for weight quantization. `gptq` settings in the .yaml file is for the weight quantization. Generally, you only need to modify ` groupsize` in it, groupsize=-1 means per-channel weight quantization, groupsize=128 means per-group weight quantization and the group size is 128(only support groupsize=128 for now).

**Comment by RanchiZhao** [comment]
> > > quant_config
> > 
> > 
> > @HandH1998 May I ask what's the purpose of `gptq` option below?
> 
> QQQ first employs smoothing, then employs gptq for weight quantization. `gptq` settings in the .yaml file is for the weight quantization. Generally, you only need to modify ` groupsize` in it, groupsize=-1 means per-channel weight quantization, groupsize=128 means per-group weight quantization and the group size is 128(only support groupsize=128 for now).

so the `dataset: wikitext2` under gptq is useless, the only calibration dataset used in gptq is in calibrate_path

**Comment by HandH1998** [comment]
> so the `dataset: wikitext2` under gptq is useless, the only calibration dataset used in gptq is in calibrate_path

`dataset: wikitext2` is used in gptq, and `calibrate_path` is used in smooth. Both are useful.

**Comment by wearegolden** [comment]
@HandH1998  Is there a specific reason you used different calibration data for smooth and gptq?

**Comment by HandH1998** [comment]
@HandH1998 I think it it better to use the same dataset. I will fix it in the next days.
