### ISSUE TITLE
Plz share some calibration dataset or examples

### ISSUE THREAD

**Issue by skykiseki** [HandH1998/QQQ#11]
I was stuck at the parameter of smooth.py,and I just wanted to run the QQQ method using my own dataset.But some error occurred.

How to organize my own dataset?

Maybe some data examples of following jsonl file are preferred.

calibrate_path: /mnt/dolphinfs/hdd_pool/docker/share/1/zhangying/datasets/pile/val.jsonl.zst

Config/W4A8.yaml

**Comment by skykiseki** [comment]
Another question, 

dataset of gptq settings in the .yaml file should be used to quantify the model weights. But I don't want to use the wiki, how to organize my own datase?????

**Comment by HandH1998** [comment]
You can organize your own dataset like https://github.com/HandH1998/QQQ/blob/2ce22a0eb3972549062b04fe74a2f627cbca1199/QQQ/smooth/smooth.py#L29-L75.
