### ISSUE TITLE
Does QQQ linear support H100?

### ISSUE THREAD

**Issue by donglinz** [HandH1998/QQQ#12]
I tried to run it on H100, but it seems there is an illegal memory access inside the kernel.

```
RuntimeError: CUDA error: an illegal memory access was encountered
```

**Comment by HandH1998** [comment]
We don't have a H100, and we don't try it on H100. But the vllm viewer seems to have tried it on H100 in https://github.com/vllm-project/vllm/pull/5218#discussion_r1631416853. Our PR has been merged into vllm now, you can try qqq in vllm on H100 and see if it can work.
