### ISSUE TITLE
Qwen2 supported？

### ISSUE THREAD

**Issue by Juelianqvq** [HandH1998/QQQ#14]

**Comment by HandH1998** [comment]
Not for now. But may support it in the next weeks.

**Comment by HandH1998** [comment]
Now QQQ employs rotation + GPTQ. So you need to support Qwen2 in [rotation](https://github.com/HandH1998/QQQ/blob/main/QQQ/rotation/rotation.py) and [GPTQ](https://github.com/HandH1998/QQQ/tree/main/QQQ/gptq/models).

**Comment by HandH1998** [comment]
@Juelianqvq Have supported Qwen2.
