### ISSUE TITLE
Qwen2-1.5B 量化后精度完全不可用

### ISSUE THREAD

**Issue by Juelianqvq** [HandH1998/QQQ#17]

**Comment by HandH1998** [comment]
详细说一下量化设置，最好分享一下量化脚本

**Comment by HandH1998** [comment]
@ 量化后的chat模型，你是用什么推理的？如果用hf，加上chat模板了吗？

**Comment by HandH1998** [comment]
examples/eval_model.py跑出来的wikitext2 PPL是多少，我明天复现一下

**Comment by HandH1998** [comment]
@Juelianqvq 我去做了实验，发现对于qwen2-1.5b-chat，rotation+gptq效果确实很差，但是smooth+gptq结果是正常的。你可以尝试`--smooth true --rotation false`。

**Comment by HandH1998** [comment]
@Juelianqvq vLLM and this repo use the same w4a8 GEMM kernel. Did you try the other qwen models, like qwen2-7b-chat?

**Comment by HandH1998** [comment]
qwen2.5的chat模板和qwen2似乎不一样，有确认过这个吗

**Comment by HandH1998** [comment]
可以在量化时加上模板试一试

**Comment by HandH1998** [comment]
最好是你模型的训练数据，因为gptq和smooth对校准数据有一定的拟合。
我明天会更新一版代码，统一smooth和gptq的数据集。

**Comment by HandH1998** [comment]
这个问题我暂时没有遇到。不过如果你的float模型是经过自己的数据微调的，最好是用自己的数据校准，而不是wiki。
