### ISSUE TITLE
bugs:   qqq_gemm.cu(183): error: identifier "__hfma2" is undefined

### ISSUE THREAD

**Issue by Andy0422** [HandH1998/QQQ#18]
Hello,
could you give me a hand on this bugs? It seems the cuda version problem...
My nvcc-V is 12.3,  and GPU is H100,  torch version is 2.3, python3.10
could you let me know your platform setting

**Comment by HandH1998** [comment]
> Hello,
> 
> could you give me a hand on this bugs? It seems the cuda version problem...
> 
> My nvcc-V is 12.3,  and GPU is H100,  torch version is 2.3, python3.10
> 
> could you let me know your platform setting
> 
> 

please refer to README
