### ISSUE TITLE
Question about building W4A8 on AMD platform

### ISSUE THREAD

**Issue by XIAOHUIL1** [HandH1998/QQQ#22]
First of all, thank you for your excellent work. We have successfully reproduced your work on Nvidia-A800. However, I don't know if this is also supported on the AMD platform. I hope to get an answer. Thanks again~

**Comment by HandH1998** [comment]
I think the answer is probably no. I developed and tested the w4a8 GEMM only on Nvidia GPU sm > 8.0.

**Comment by XIAOHUIL1** [comment]
> I think the answer is probably no. I developed and tested the w4a8 GEMM only on Nvidia GPU sm > 8.0.

This is a pity, but thank you for your outstanding contribution.
