### ISSUE TITLE
[QST] Speedup of GEMM

### ISSUE THREAD

**Issue by Hongbosherlock** [HandH1998/QQQ#3]
![image](https://github.com/HandH1998/QQQ/assets/27813268/5a1fadcf-e474-4a73-8f38-29e9eafe7b7b)

Why is `W4A8` faster than `W8A8`?  `W4A8` needs some additional operations before performing  `INT8 GEMM`
Does `W8A8` here refer to `per-token+per-channel`?

**Comment by HandH1998** [comment]
@Hongbosherlock When the batch size is small, LLM inference becomes memory-bound. In this scenario, using w4a8 can reduce memory bandwidth usage by half compared to w8a8.
w8a8 here refers to per-token activation + per-tensor weight.

**Comment by Hongbosherlock** [comment]
> @Hongbosherlock When the batch size is small, LLM inference becomes memory-bound. In this scenario, using w4a8 can reduce memory bandwidth usage by half compared to w8a8. w8a8 refers to the scenario without dequantization, focusing entirely on GEMM (General Matrix Multiply) time.

I thought the batch size is `1` , and GEMM is (m,k) x (n,k) in this pic .
What's the batch size in this pic?

**Comment by HandH1998** [comment]
@HandH1998 You are right. I should refer to `num of input tokens`.

**Comment by Hongbosherlock** [comment]
> @Hongbosherlock You are right. I should refer to `num of input tokens`.

Is the pic about profiling single GEMM instead of LLM inference?
I still don't understand why W4A8 is faster than W8A8 on GEMM (M,K) x (K,N).

**Comment by HandH1998** [comment]
> > @Hongbosherlock You are right. I should refer to `num of input tokens`.
> 
> Is the pic about profiling single GEMM instead of LLM inference? I still don't understand why W4A8 is faster than W8A8 on GEMM (M,K) x (K,N).

Yes, it is profiling single GEMM. 
GEMM  needs fetch weights from HBM, and W4A8 can save the memory access time by half compared to W8A8.

**Comment by Hongbosherlock** [comment]
> GEMM needs fetch weights from HBM, and W4A8 can save the memory access time by half compared to W8A8.

In my opinion, the process is as follows:
> Every two int4 elements are packed into one int8 element.
- W4A8: (1)load activition(M,K)  and weight (K/2,N) ,    (2) int4->int8      (3)int8 gemm
- W8A8: (1)load activition(M,K)  and weight (K,N)    ,     (2) int8 gemm

But in the above picture, why does W4A8 perform so better when `M` is small.  When the `number of input tokens`(M) is 1, the speedup of `W4A8` is `3.5`, and the speedup of `W8A8` is `1.5`. The former is more than **twice** the performance of the latter. 

If there are any misunderstandings on my part, please point them out. Thanks!

**Comment by HandH1998** [comment]
@Hongbosherlock  As the pic shown, the weight size is fixed to `N=8192, K=21760`. The `num of input tokens` M only affects the activation size (M, K).

**Comment by Hongbosherlock** [comment]
W4A8: 
- `t1`: load activition(M,K) and weight (K/2,N)        
- `t2`:  int4->int8                                                     
- `t3`:int8 gemm                                                   

time of W4A8 GEMM:` t1+t2+t3`

W8A8: 
- `T1`:load activition(M,K) and weight (K,N)          
- `T2`:int8 gemm                                                       

time of W4A8 GEMM:`T1+T2`

for int8 gemm:`t3=T2`

In ths pic `(T1+T2)/(t1+t2+t3)=3.5/1.5>2` 
 we can get:  `T1 > 2t1+2t2+t3`, I don't understand how it could be ?

**Comment by HandH1998** [comment]
calculation and memory access have overlap, the execution time cannot be calculated like the above in practice发自我的 iPhone在 2024年7月3日，20:16，leoneo ***@***.***> 写道：﻿
W4A8:

t1: load activition(M,K) and weight (K/2,N)
t2:  int4->int8
t3:int8 gemm

time of W4A8 GEMM: t1+t2+t3
W8A8:

T1:load activition(M,K) and weight (K,N)
T2:int8 gemm

time of W4A8 GEMM:T1+T2
for int8 gemm:t3=T2
In ths pic (T1+T2)/(t1+t2+t3)=3.5/1.5>2
we can get:  T1 > 2t1+2t2+t3, I don't understand how it could be ?

**Comment by HandH1998** [comment]
> you mean:
> 
> > W4A8 can save the memory access time by half compared to W8A8.
> 
> 
> 
> 
> 
> W4A8: 
> 
> - `t1`: load activition(M,K) and weight (K/2,N)        
> 
> - `t2`:  int4->int8                                                     
> 
> - `t3`:int8 gemm                                                   
> 
> 
> 
> time of W4A8 GEMM:` t1+t2+t3`
> 
> 
> 
> W8A8: 
> 
> - `T1`:load activition(M,K) and weight (K,N)          
> 
> - `T2`:int8 gemm                                                       
> 
> 
> 
> time of W4A8 GEMM:`T1+T2`
> 
> 
> 
> for int8 gemm:`t3=T2`
> 
> 
> 
> In ths pic `(T1+T2)/(t1+t2+t3)=3.5/1.5>2` 
> 
>  we can get:  `T1 > 2t1+2t2+t3`, I don't understand how it could be ?

calculation and memory access have overlap, the execution time cannot be calculated like the above in practice

**Comment by Hongbosherlock** [comment]
> calculation and memory access have overlap, the execution time cannot be calculated like the above in practice

How is the performance of W8A8 tested, and which kernel is used?

**Comment by HandH1998** [comment]
@Hongbosherlock 
We used cuBlas W4A8  GEMM https://github.com/AniZpZ/AutoSmoothQuant/tree/main/csrc/int8gemm.

**Comment by Hongbosherlock** [comment]
> @Hongbosherlock We used cuBlas W4A8 GEMM https://github.com/AniZpZ/AutoSmoothQuant/tree/main/csrc/int8gemm.

How can I profile the w4a8 and w8a8 GEMM kernel like you do this pic?

**Comment by HandH1998** [comment]
See [https://github.com/HandH1998/QQQ/issues/2#issuecomment-2179921604](url).

**Comment by brisker** [comment]
> See [https://github.com/HandH1998/QQQ/issues/2#issuecomment-2179921604](url).

w8a8 quantized model can also be exported in QQQ repo? Simply modify wbits from 4 to 8?

**Comment by HandH1998** [comment]
> > See [https://github.com/HandH1998/QQQ/issues/2#issuecomment-2179921604](url).
> 
> w8a8 quantized model can also be exported in QQQ repo? Simply modify wbits from 4 to 8?

There are many diffs between w4a8 and w8a8, and you cannot modify wbits to 8 in QQQ.

**Comment by brisker** [comment]
> > you mean:
> > > W4A8 can save the memory access time by half compared to W8A8.
> > 
> > 
> > W4A8:
> > 
> > * `t1`: load activition(M,K) and weight (K/2,N)
> > * `t2`:  int4->int8
> > * `t3`:int8 gemm
> > 
> > time of W4A8 GEMM:` t1+t2+t3`
> > W8A8:
> > 
> > * `T1`:load activition(M,K) and weight (K,N)
> > * `T2`:int8 gemm
> > 
> > time of W4A8 GEMM:`T1+T2`
> > for int8 gemm:`t3=T2`
> > In ths pic `(T1+T2)/(t1+t2+t3)=3.5/1.5>2`
> > we can get:  `T1 > 2t1+2t2+t3`, I don't understand how it could be ?
> 
> calculation and memory access have overlap, the execution time cannot be calculated like the above in practice
@HandH1998 
Regarding the w4a8-gs128 setting, why does QQQ use the w4->fp16->w8 pipeline, but not the w4->w8 pipeline in QServe, since  w4->fp16->w8  seems to be slower?

**Comment by HandH1998** [comment]
@brisker Actually, our w4a8-g128 used w4->w8 directly, as we fused scale of w4->fp16 with the scale of fp16->w8 offline. Refer to QQQ paper `These
two steps are elegantly merged into a single operation, FusedDequantQuant, by dividing the
per-group scale by the per-channel scale, as illustrated in Figure 4.`.

**Comment by brisker** [comment]
@HandH1998 
Even armed with fused-dequant, qqq seem  to have addtional fp16-->int8 process, so for w4a8 with group=128, **on the cuda core**, qqq has to do **two** addtional ops: fused-dequant, fp16->int8. 
But the pipline in QServe, or [here](https://arxiv.org/pdf/2405.14597), they seems to have **only one** addtional ops on cuda core:
integer scale multiplied by int8-gemm results in [here](https://arxiv.org/pdf/2405.14597) or int4->int8 using a interger scale mulplication in QServe.

So theoretically, will those two methods be faster than QQQ?(group_size=128 case)

**Comment by HandH1998** [comment]
@brisker Yes, a integer scale may be a better choice, but I'm not sure how it affect the accuracy. I will try the integer scale of QQQ later.

**Comment by brisker** [comment]
@HandH1998 
Regarding the speed test in qqq paper, is the gptq-reorder true or false? I mean, in the following codes:
https://github.com/HandH1998/QQQ/blob/49f06e0b47c606ca2c5558ade0805b0609d57a8f/QQQ/gptq/gptq.py#L181-L184

In QQQ-w4a8 kernel, will the speed of 

`g_idx = [perm[i] // groupsize for i in range(self.columns)]` 

and 

`g_idx = [i // groupsize for i in range(self.columns)]`   **be different in these two cases?**

**Comment by brisker** [comment]
> @HandH1998
> 
> 1. Regarding the speed test in qqq paper, is the gptq-reorder true or false? I mean, in the following codes:
> 
> https://github.com/HandH1998/QQQ/blob/49f06e0b47c606ca2c5558ade0805b0609d57a8f/QQQ/gptq/gptq.py#L181-L184
> 
> In QQQ-w4a8 kernel, will the speed of
> 
> `g_idx = [perm[i] // groupsize for i in range(self.columns)]`
> 
> and
> 
> `g_idx = [i // groupsize for i in range(self.columns)]` **be different in these two cases?**
> 
> 2. In the following codes:
>    https://github.com/HandH1998/QQQ/blob/49f06e0b47c606ca2c5558ade0805b0609d57a8f/QQQ/gptq/quant.py#L36-L39
> 
> for group_size=-1, qqq w4 is in [-7,7] for group_size=128, qqq w4 is in [0,15], and after substracting **fixed** zero-point=8, comes at [-8,7]
> 
> Is that true? There seems to be slight difference between these two cases: 15 unique numbers and 16 unique numbers, why is that?

@HandH1998

**Comment by HandH1998** [comment]
@brisker Sorry for the late reply.
1. `gptq-reorder` is true. You can refer to [https://github.com/IST-DASLab/gptq?tab=readme-ov-file#new-features](url) for more info about it. And it doesn't affect w4a8 kernel's speed. 
2. Yes, you are right. For `group_size=-1`, we use sym quant to set w4 at [-7, 7], then we only need multiply the quant scale to dequant without subtracting the fixed zero point 8. For `group_size=128`, although we also use sym quant, the per-group w4a8 kernel's `FastInt4toFp16` requires w4 to be uint4, so we set w4 at [0, 15].

**Comment by brisker** [comment]
@HandH1998 
I do not quiet understand why you have a scale_extra for your w4a8-gs128 kernel here:
https://github.com/HandH1998/QQQ/blob/49f06e0b47c606ca2c5558ade0805b0609d57a8f/QQQ/gptq/gptq.py#L206-L216

1. Given a fp16 weight, assume it is already quantized and dequantized into a w4-gs128 weight, why bother to get the dequantized-w4-gs128-weight's per-channel quanti scales? Do you mean you need to quant_dequant it **again** in per-channel style?(This will definitely harm the accuracy)

    In my understanding, `w4_gs128 = quant_and_dequant(w_fp16)`  is totally enough, with no need to add any other scales.
    
   Is that one scale splitted by you into two? so you have to generate two scales?

2. In the paper, you mentioned you used the fusedquantDequant pipeline, but why there still exists two scales when packing the model?

**Comment by HandH1998** [comment]
@brisker `s_channel` is used in the dequant from INT32 to FP16 after INT8 GEMM. `s_group` is used in the weight dequant from INT4 to INT8 before INT8 GEMM.
